/**
 * Datos estáticos de fallback para los tests psicométricos.
 * Se usan cuando la base de datos no está disponible (ej: Vercel sin DB remota).
 */
export const fallbackTests = [
  // --- Nivel Básico ---
  {
    id: 'fallback-luscher',
    name: 'Test de Colores de Lüscher',
    type: 'proyectivo',
    level: 'basico',
    price: 0.0,
    isPremium: false,
    duration: 5,
    active: true,
    structure: JSON.stringify({ description: 'Test de colores no verbal para estado emocional.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-disc',
    name: 'Test de Cleaver / Perfil DISC',
    type: 'DISC',
    level: 'basico',
    price: 0.0,
    isPremium: false,
    duration: 15,
    active: true,
    structure: JSON.stringify({ description: 'Estilo de trabajo y comportamiento organizacional.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-allport',
    name: 'Test de Valores de Allport',
    type: 'axiológico',
    level: 'basico',
    price: 0.0,
    isPremium: false,
    duration: 20,
    active: true,
    structure: JSON.stringify({ description: 'Motivadores y alineación cultural.' }),
    createdAt: new Date(),
  },

  // --- Nivel Intermedio ---
  {
    id: 'fallback-moss',
    name: 'Test de Moss',
    type: 'habilidades_sociales',
    level: 'intermedio',
    price: 19.99,
    isPremium: true,
    duration: 30,
    active: true,
    structure: JSON.stringify({ description: 'Adaptabilidad y habilidades de supervisión.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-zavic',
    name: 'Test de Zavic',
    type: 'valores',
    level: 'intermedio',
    price: 19.99,
    isPremium: true,
    duration: 20,
    active: true,
    structure: JSON.stringify({ description: 'Valores e intereses. Orientado a Integridad.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-kostick',
    name: 'Test de Kostick',
    type: 'inventario',
    level: 'intermedio',
    price: 19.99,
    isPremium: true,
    duration: 30,
    active: true,
    structure: JSON.stringify({ description: 'Inventario de percepción y preferencias laborales.' }),
    createdAt: new Date(),
  },

  // --- Nivel Avanzado ---
  {
    id: 'fallback-raven',
    name: 'Test de Raven - Matrices Progresivas',
    type: 'inteligencia',
    level: 'avanzado',
    price: 29.99,
    isPremium: true,
    duration: 45,
    active: true,
    structure: JSON.stringify({ description: 'Inteligencia no verbal.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-terman',
    name: 'Test de Terman-Merrill',
    type: 'inteligencia',
    level: 'avanzado',
    price: 29.99,
    isPremium: true,
    duration: 50,
    active: true,
    structure: JSON.stringify({ description: 'Coeficiente Intelectual (CI).' }),
    createdAt: new Date(),
  },

  // --- Nivel Clínico/Premium ---
  {
    id: 'fallback-16pf',
    name: 'Test 16 PF de Cattell',
    type: 'personalidad',
    level: 'premium',
    price: 49.99,
    isPremium: true,
    duration: 60,
    active: true,
    structure: JSON.stringify({ description: '16 Factores de la Personalidad.' }),
    createdAt: new Date(),
  },
  {
    id: 'fallback-mmpi',
    name: 'MMPI-2',
    type: 'personalidad_clinico',
    level: 'premium',
    price: 49.99,
    isPremium: true,
    duration: 120,
    active: true,
    structure: JSON.stringify({ description: 'Inventario Multifásico de Personalidad de Minnesota.' }),
    createdAt: new Date(),
  },
];
