import Image from 'next/image';
import manifest from '../../../public/assets/brand-manifest.json';

/**
 * Auto-couples a vacancy's `empresa` (free string) with the brand-manifest
 * generated by `scripts/process-brand-assets.js`.
 *
 * If the slugified name matches a client logo, renders the logo inside a
 * uniform white card. Otherwise falls back to a clean text tag.
 */

type ClientEntry = { slug: string; original: string; hasAlpha: boolean; format: string };
const CLIENT_SLUGS: Set<string> = new Set((manifest.clientes as ClientEntry[]).map((c) => c.slug));

function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** Some empresa names need a manual alias to match manifest slugs. */
const ALIASES: Record<string, string> = {
  'goncalves-de-mexico': 'goncalves',
  'prisma': 'prisma-industrial',
};

export function resolveEmpresaLogoSlug(empresa: string): string | null {
  const direct = slugify(empresa);
  if (CLIENT_SLUGS.has(direct)) return direct;
  const aliased = ALIASES[direct];
  if (aliased && CLIENT_SLUGS.has(aliased)) return aliased;
  // Loose match: try first token
  const firstToken = direct.split('-')[0];
  if (firstToken && CLIENT_SLUGS.has(firstToken)) return firstToken;
  return null;
}

interface Props {
  empresa: string;
  size?: 'sm' | 'md' | 'lg';
}

const SIZES = {
  sm: { card: 'w-24 h-12 p-2', img: { w: 80, h: 32 } },
  md: { card: 'w-32 h-14 p-2.5', img: { w: 110, h: 40 } },
  lg: { card: 'w-44 h-20 p-4', img: { w: 160, h: 56 } },
} as const;

export function EmpresaLogo({ empresa, size = 'md' }: Props) {
  const slug = resolveEmpresaLogoSlug(empresa);
  const s = SIZES[size];

  if (!slug) {
    // Text fallback — keep consistent height for layout stability
    return (
      <div
        className={`${s.card} rounded-xl bg-white/5 border border-white/10 flex items-center justify-center`}
        aria-label={empresa}
      >
        <span className="text-slate-300 font-bold text-xs uppercase tracking-wider text-center leading-tight">
          {empresa}
        </span>
      </div>
    );
  }

  return (
    <div
      className={`${s.card} rounded-xl bg-white flex items-center justify-center shadow-sm`}
      aria-label={empresa}
    >
      <picture className="flex items-center justify-center w-full h-full">
        <source srcSet={`/assets/clientes/${slug}.avif`} type="image/avif" />
        <source srcSet={`/assets/clientes/${slug}.webp`} type="image/webp" />
        <Image
          src={`/assets/clientes/${slug}.png`}
          alt={empresa}
          width={s.img.w}
          height={s.img.h}
          className="object-contain max-w-full max-h-full"
          loading="lazy"
        />
      </picture>
    </div>
  );
}
